name: portfolio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  splashscreen: ^1.2.0
  url_launcher: ^5.5.0
  url_launcher_web: ^0.1.2
  http: ^0.12.2
  provider: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/intro.png
    - assets/images/github.png
    - assets/images/linkedin.png
    - assets/images/hackerrank.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 800
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 400